Repository CS-DesignParLesTests/cqrs-sample, pull requests merged in 2021-04, with the labels that each got.

#4 Add github actions
  .github/workflows/build.yml
  .github/workflows/linterAndFormatter.yml
  .github/workflows/runTest.yml
  package.json
  src/book/book/book.controller.ts
  src/book/book/book.module.ts
Labels: enhancement

#5 OpenAPI (swagger) configuration initialization
  package.json
  src/main.ts
  yarn.lock
Labels: enhancement

#10 Book CQRS, Commands : Create / Delete, Queries : Get / GetAll
  src/app.module.ts
  src/book/books.controller.ts
  src/book/books.module.ts
  src/book/dto/create-book.dto.ts
  src/books/books.controller.ts
  src/books/books.module.ts
  src/books/commands/handlers/create.book.spec.ts
  src/books/commands/handlers/create.book.ts
  src/books/commands/handlers/delete.book.spec.ts
  src/books/commands/handlers/delete.book.ts
  src/books/commands/implements/create.book.ts
  src/books/commands/implements/delete.book.ts
  src/books/commands/indexCommand.ts
  src/books/dto/create-book.dto.ts
  src/books/entities/book.entity.ts
  src/books/queries/handlers/get.book.spec.ts
  src/books/queries/handlers/get.book.ts
  src/books/queries/handlers/list.books.spec.ts
  src/books/queries/handlers/list.books.ts
  src/books/queries/implements/get.book.ts
  src/books/queries/implements/list.books.ts
  src/books/queries/indexQuery.ts
  src/books/repository/book-repository.ts
  src/books/repository/memory/book-repository-memory.adapter.ts
Labels: Books

#9 Create CQRS based User class
  src/app.module.ts
  src/users/commands/handlers/create-user.handler.spec.ts
  src/users/commands/handlers/create-user.handler.ts
  src/users/commands/handlers/delete-user.handler.ts
  src/users/commands/handlers/delete-user.spec.ts
  src/users/commands/handlers/index.ts
  src/users/commands/implements/create-user.command.ts
  src/users/commands/implements/delete-user.command.ts
  src/users/commands/implements/index.ts
  src/users/dto/create-user.dto.ts
  src/users/dto/update-user.dto.ts
  src/users/entities/user.entity.ts
  src/users/queries/handlers/get-user-by-username.handler.spec.ts
  src/users/queries/handlers/get-user-by-username.handler.ts
  src/users/queries/handlers/get-users.handler.spec.ts
  src/users/queries/handlers/get-users.handler.ts
  src/users/queries/handlers/index.ts
  src/users/queries/implements/get-user-by-username.query.ts
  src/users/queries/implements/get-users.query.ts
  src/users/queries/implements/index.ts
  src/users/repositories/users-repository-memory.adapter.spec.ts
  src/users/repositories/users-repository-memory.adapter.ts
  src/users/repositories/users-repository.ts
  src/users/users.controller.spec.ts
  src/users/users.controller.ts
  src/users/users.module.ts
  src/users/users.service.spec.ts
  src/users/users.service.ts
Labels: User

#15 Linter rules
  .eslintrc.js
  src/main.ts
  src/users/commands/handlers/create-user.handler.spec.ts
  src/users/commands/handlers/delete-user.handler.spec.ts
  src/users/entities/user.entity.ts
  src/users/queries/handlers/get-user-by-username.handler.spec.ts
Labels: config

#17 BookOwnership Module Preparation
  src/app.module.ts
  src/book-ownerships/book-ownerships.controller.spec.ts
  src/book-ownerships/book-ownerships.controller.ts
  src/book-ownerships/book-ownerships.module.ts
  src/book-ownerships/book-ownerships.service.spec.ts
  src/book-ownerships/book-ownerships.service.ts
  src/book-ownerships/commands/handlers/index.ts
  src/book-ownerships/commands/implements/create-book-ownership.command.ts
  src/book-ownerships/commands/implements/delete-book-ownership.command.ts
  src/book-ownerships/commands/implements/index.ts
  src/book-ownerships/dto/create-book-ownership.dto.ts
  src/book-ownerships/dto/update-book-ownership.dto.ts
  src/book-ownerships/entities/book-ownership.entity.ts
  src/book-ownerships/queries/handlers/index.ts
  src/book-ownerships/queries/implements/get-book-ownership-by-user-and-id.query.ts
  src/book-ownerships/queries/implements/get-book-ownership-by-user.query.ts
  src/book-ownerships/queries/implements/index.ts
  src/book-ownerships/repositories/book-ownerships-repository-memory.adapter.ts
  src/book-ownerships/repositories/book-ownerships-repository.ts
  src/users/users.controller.ts
Labels: Bookownership

#12 Bdd implementation
  docker-compose.yml
  package.json
  src/app.module.ts
  src/books/books.module.ts
  src/books/commands/handlers/create-book.handler.spec.ts
  src/books/commands/handlers/create-book.handler.ts
  src/books/commands/handlers/delete-book.handler.spec.ts
  src/books/commands/handlers/delete-book.handler.ts
  src/books/commands/handlers/update-book.handler.spec.ts
  src/books/commands/handlers/update-book.handler.ts
  src/books/entities/book.entity.ts
  src/books/queries/handlers/get-book.handler.spec.ts
  src/books/queries/handlers/get-book.handler.ts
  src/books/queries/handlers/get-books.handler.spec.ts
  src/books/queries/handlers/get-books.handler.ts
  src/books/repository/book-repository.ts
  src/books/repository/memory/book-repository-memory.adapter.spec.ts
  src/books/repository/memory/book-repository-memory.adapter.ts
  src/books/repository/typeorm/book-repository-typeorm.adapter.ts
  src/users/entities/user.entity.ts
  src/users/repositories/users-repository-typeorm.adapter.ts
  src/users/users.module.ts
  yarn.lock
Labels: Bdd

#18 Handle incomplete payloads in [CREATE] scenarios
  src/books/books.controller.ts
  src/main.ts
  src/users/dto/create-user.dto.ts
  src/users/users.controller.ts
Labels: User, bug, documentation

#20 Update property names on BookOwnership types
  src/book-ownerships/dto/create-book-ownership.dto.ts
  src/book-ownerships/entities/book-ownership.entity.ts
Labels: Bookownership

#22 Operational docker app and database + fix entity types to match with database types
  .dockerignore
  Dockerfile
  docker-compose.yml
  mysqldatabase/Dockerfile
  mysqldatabase/init_1_db_role.sql
  mysqldatabase/init_2_db_data.sql
  src/app.module.ts
  src/users/entities/user.entity.ts
Labels: Bdd, Bookownership, Books, Docker, User, config, enhancement

#14 add badge to readme
  README.md
Labels: documentation

#25 Implement BookOwnership Handlers with TDD
  src/book-ownerships/book-ownerships.module.ts
  src/book-ownerships/book-ownerships.service.ts
  src/book-ownerships/commands/handlers/create-book-ownership.handler.spec.ts
  src/book-ownerships/commands/handlers/create-book-ownership.handler.ts
  src/book-ownerships/commands/handlers/delete-book-ownership.handler.spec.ts
  src/book-ownerships/commands/handlers/delete-book-ownership.handler.ts
  src/book-ownerships/commands/handlers/index.ts
  src/book-ownerships/entities/book-ownership.entity.ts
  src/book-ownerships/queries/handlers/get-book-ownership-by-user-and-id.handler.spec.ts
  src/book-ownerships/queries/handlers/get-book-ownership-by-user-and-id.handler.ts
  src/book-ownerships/queries/handlers/get-book-ownerships-by-user.handler.spec.ts
  src/book-ownerships/queries/handlers/get-book-ownerships-by-user.handler.ts
  src/book-ownerships/queries/handlers/index.ts
  src/book-ownerships/queries/implements/get-book-ownerships-by-user.query.ts
  src/book-ownerships/queries/implements/index.ts
  src/book-ownerships/repositories/memory/book-ownerships-repository-memory.adapter.ts
  src/main.ts
  src/users/users.module.ts
Labels: Bookownership, enhancement

#27 fix(user) : add missing update in index of handlers
  src/users/commands/handlers/index.ts
Labels: User, bug

#29 Update book ownership CQRS
  src/book-ownerships/book-ownerships.controller.ts
  src/book-ownerships/book-ownerships.service.ts
  src/book-ownerships/commands/handlers/index.ts
  src/book-ownerships/commands/handlers/update-book-ownership.handler.spec.ts
  src/book-ownerships/commands/handlers/update-book-ownership.handler.ts
  src/book-ownerships/commands/implements/index.ts
  src/book-ownerships/commands/implements/update-book-ownership.command.ts
  src/book-ownerships/repositories/book-ownerships-repository.ts
  src/book-ownerships/repositories/memory/book-ownerships-repository-memory.adapter.ts
Labels: Bookownership

#26 Separate db queries with mongodb for books and users
  docker-compose.yml
  package.json
  src/app.module.ts
  src/books/books.module.ts
  src/books/repositories/typeorm/book-repository-typeorm.adapter.ts
  src/books/schemas/book.schema.ts
  src/users/repositories/users-repository-typeorm.adapter.ts
  src/users/schemas/user.schema.ts
  src/users/users.module.ts
  yarn.lock
Labels: Bdd, Books, User, enhancement

#23 BDD for book-ownerships (SQL + mongo)
  mysqldatabase/init_2_db_data.sql
  src/app.module.ts
  src/book-ownerships/book-ownerships.module.ts
  src/book-ownerships/entities/book-ownership.entity.ts
  src/book-ownerships/repositories/book-ownerships-repository-typeorm.adapter.ts
  src/book-ownerships/repositories/memory/book-ownerships-repository-memory.adapter.ts
  src/book-ownerships/schemas/book-ownership.schema.ts
Labels: Bdd, Bookownership
